development:
  adapter: postgresql
  encoding: unicode
  database: don_development
  template: template0
  pool: 5
  username: DonAndMimi
  password: donnief3

test:
  adapter: postgresql
  encoding: unicode
  database: don_test
  template: template0
  pool: 5
  username: DonAndMimi
  password: donnief3